import type { Metadata } from "next";
import { Affix, ThemeProvider, ThemeScript } from "@kadoui/react";

import "./globals.css";
import { ChevronUpIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className="antialiased">
        <ThemeProvider>
          {children}

          <Affix className="affix btn btn-fill bottom-3 right-3" viewportOffset={1}>
            <ChevronUpIcon className="element-icon-size" />
          </Affix>
        </ThemeProvider>
      </body>
    </html>
  );
}
